-- Add SHORTLISTED status for two-stage hackathon workflow
ALTER TABLE `claims`
  MODIFY `status` ENUM('IN_PROGRESS', 'SUBMITTED', 'SHORTLISTED', 'ACCEPTED', 'REVISION_REQUESTED', 'REJECTED') NOT NULL DEFAULT 'IN_PROGRESS';
